plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'org.parchmentmc.librarian.forgegradle' version '1.2.0'
}

version = mod_version
group = mod_group_id
archivesBaseName = mod_name
String is_mixin = enable_mixin
String mixin_file = mod_id + ".mixin.json"
String mixin_refmap_file = mod_id + ".mixin.refmap.json"

Date date = new Date()

base {
    archivesName = mod_name
}
java {
    withSourcesJar()
}
sourcesJar {
    from sourceSets.main.java // 只包含 Java 源文件
    include '**/*.java' // 确保只包括 .java 文件
    exclude(
            '**/.cache/**', // 排除 .cache 文件夹
            '**/assets/**', // 排除 assets 文件夹
            '**/data/**' // 排除 data 文件夹
    )
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE // 排除重复的文件
    archiveClassifier.set('sources') // 设置源代码 JAR 文件的后缀
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

jarJar.enable()
reobf {
    jarJar {}
}

tasks.jarJar.configure {
    archivesBaseName = mod_name
    version = mod_version
}

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: mapping_channel, version: mapping_version
    enableEclipsePrepareRuns = false
    enableIdeaPrepareRuns = false

    copyIdeResources = true
    // generateRunFolders = true
    accessTransformer = file('src/main/resources/META-INF/' + at_file)

    runs {
        configureEach {
            workingDirectory project.file(workingDirectory)
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
			if(is_mixin == "true"){
				property 'mixin.env.remapRefMap', 'true'
				property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
			}

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            workingDirectory project.file(client_dir)
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--username', run_user
            if (is_mixin == "true") {
				property 'mixin.env.remapRefMap', 'true'
				property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
                arg '-mixin.config='+mixin_file
            }
        }

        server {
            workingDirectory project.file(server_dir)
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
            if (is_mixin == "true") {
				property 'mixin.env.remapRefMap', 'true'
				property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
				arg '-mixin.config='+mixin_file
            }
        }

        gameTestServer {
            workingDirectory project.file(gameTestServer_dir)
            property 'forge.enabledGameTestNamespaces', mod_id
            if (is_mixin == "true") {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
                arg '-mixin.config='+mixin_file
            }
        }

        data {
            workingDirectory project.file(data_dir)
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            if (is_mixin == "true") {
				property 'mixin.env.remapRefMap', 'true'
				property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
                arg '-mixin.config='+mixin_file
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = 'https://maven.parchmentmc.org' }
    maven { url =  'https://www.cursemaven.com/'  }
    flatDir {
        dir 'libs'
    }
}
dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    if(is_mixin == "true") {
        annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    }
	
//    implementation('com.h2database:h2:2.2.224')
//    implementation("org.xerial:sqlite-jdbc:[3.49.1.0,)")
    runtimeOnly fg.deobf("curse.maven:lan-server-properties-387365:4776657")
    runtimeOnly fg.deobf("curse.maven:placebo-283644:6274231")
    implementation fg.deobf("curse.maven:apothic-attributes-898963:5634071")

    compileOnly("blank:jmp123-all:1.0.0")
    implementation fg.deobf(jarJar("blank:jiucore-1.20.1:[0.0.1,)") {
        jarJar.pin(it, "0.0.1")
    })
}

mixin {
    if (is_mixin == "true") {
        add sourceSets.main, mixin_refmap_file
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_name,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : 1,
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': date.format("yyyy/MM/dd_HH:mm:ss")
        ])
    }
}
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version:       minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version:           forge_version,
            forge_version_range:     forge_version_range,
            loader_version_range:    loader_version_range,
            mod_id:                  mod_id,
            mod_name:                mod_name,
            mod_license:             mod_license,
            mod_version:             mod_version,
            mod_authors:             mod_authors,
            mod_description:         mod_description,
            core_version:            core_version
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}
