# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=7890
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=7890

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.18.2
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.18.2]
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=40.2.18
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[40,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[40,)


# The mappings can be changed at any time, and must be in the following format.
# Channel:   Version:
# parchment  YYYY.MM.DD-MCVersion  Open community-sourced parameter names and javadocs layered on top of official
# official   MCVersion  Official field/method names from Mojang mapping files
#
# You must be aware of the Mojang license when using the 'official' mappings.
# See more information here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
#
# Use non-default mappings at your own risk. they may not always work.
# Simply re-run your setup task after changing the mappings to update your workspace.
#    mappings channel: 'official', version: '1.18.2'
mapping_channel=parchment
#mapping_channel=official

# The mapping version to query from the mapping channel.
# This must match the format required by the mapping channel.
mapping_version=2022.11.06-1.18.2
#mapping_version=1.18.2

at_file=accessTransformer.cfg

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=email
# The human-readable display name for the mod.
mod_name=Inbox
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=GNU AGPL-3.0
# The mod version. See https://semver.org/
mod_version=1.18.2-1.0.0-a0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=cat.jiu.email
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=small_jiu
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=a inbox mod

## Run Properties
run_user=small_jiu
workingDirectory=run
client_dir=run/client
server_dir=run/server
gameTestServer_dir=run/server_test
data_dir=run/data
