modLoader="javafml"
loaderVersion="[36,)"
license="GNU AGPL 3.0 license"
[[mods]]
modId="email"
version="2.0.0"
displayName="Email"
logoFile="logo.png"
credits=""
authors="small_jiu"
description='''
a inbox mod
'''
[[dependencies.email]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.email]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
