modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GNU AGPL 3.0 license"
[[mods]]
modId="email"
version="1.20.1-1.0.0"
displayName="Email"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
#credits="" #optional
authors="small_jiu"
description='''a inbox mod'''
[[dependencies.email]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.email]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
